### ISSUE TITLE
Can't install for Symfony 2.5.0

### ISSUE THREAD

**Issue by ajaypatelbardoli** [matthiasnoback/MicrosoftTranslatorBundle#3]
Can't install this bundle for Symfony 2.5.0. got this error

Problem 1
    - Conclusion: don't install symfony/symfony v2.3.16
    - Conclusion: don't install symfony/symfony v2.3.15
    - Conclusion: don't install symfony/symfony v2.3.14
    - Conclusion: don't install symfony/symfony v2.3.13
    - Conclusion: don't install symfony/symfony v2.3.12
    - Conclusion: don't install symfony/symfony v2.3.11
    - Conclusion: don't install symfony/symfony v2.3.10
    - Conclusion: don't install symfony/symfony v2.3.9
    - Conclusion: don't install symfony/symfony v2.3.8
    - Conclusion: don't install symfony/symfony v2.3.7
    - Conclusion: don't install symfony/symfony v2.3.6
    - Conclusion: don't install symfony/symfony v2.3.5
    - Conclusion: don't install symfony/symfony v2.3.4
    - Conclusion: don't install symfony/symfony v2.3.3
    - Conclusion: don't install symfony/symfony v2.3.2
    - Conclusion: don't install symfony/symfony v2.3.1
    - sensio/framework-extra-bundle v3.0.0 requires symfony/framework-bundle ~2.4 -> satisfiable by symfony/symfony[v2.4.6], symfony/framework-bundle[v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.5.0].
    - sensio/framework-extra-bundle v3.0.0 requires symfony/framework-bundle ~2.4 -> satisfiable by symfony/symfony[v2.4.6], symfony/framework-bundle[v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.5.0].
    - sensio/framework-extra-bundle v3.0.1 requires symfony/framework-bundle ~2.5 -> satisfiable by symfony/framework-bundle[v2.5.0].
    - Can only install one of: symfony/symfony[v2.3.0, v2.4.6].
    - don't install symfony/framework-bundle v2.4.0|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.4.1|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.4.2|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.4.3|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.4.4|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.4.5|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.4.6|don't install symfony/symfony v2.3.0
    - don't install symfony/framework-bundle v2.5.0|don't install symfony/symfony v2.3.0
    - Installation request for symfony/symfony 2.3.* -> satisfiable by symfony/symfony[v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.2, v2.3.3, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9].
    - Installation request for sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[v3.0.0, v3.0.1].

**Comment by krombox** [comment]
the same for Symfony 2.7.6

**Comment by matthiasnoback** [comment]
Thanks for reporting.

**Comment by krombox** [comment]
This is not fix an issue at all. At least for Symfony >= 2.7.5. It required doctrine/common: ~2.4, when matthiasnoback/microsoft-translator -> doctrine/common: >=2.2,<2.4-dev.
So please, change  "matthiasnoback/microsoft-translator": "0.*", to "dev-master" or make new one branch v0.4.3 with "doctrine/common": "~2.2". Hope it is clear. Thanks!

**Comment by matthiasnoback** [comment]
If you supply the proper fix, I'll merge it and release a new version. Could you make the library compatible with all Symfony and Doctrine Common versions please?

**Comment by krombox** [comment]
First, you need to create new release  v0.4.3 from master there: https://github.com/matthiasnoback/microsoft-translator. v0.4.2 required doctrine/common: >=2.2,<2.4-dev, dev-master is ok.
Then, i`l make pull request for this repo. Seams like it must working from symfony 2.2. Please make first step

**Comment by matthiasnoback** [comment]
@krombox Now I get it :) I guess it's all about releasing new versions of this. Which I just did!

**Comment by krombox** [comment]
Now all is ok. My bundle normally installed yours as dependency from composer. Thanks!

**Comment by matthiasnoback** [comment]
Okay, you're welcome!
